apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aegis-backend-secrets
  namespace: aegis
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: aegis-backend-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: /aegis/shared/backend
