apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - clustersecretstore.yaml
  - externalsecret.yaml
  - deployments.yaml
  - services.yaml
  - ingress.yaml
  - networkpolicies.yaml
  - hpa.yaml
